name: "[app] skillpedia - CI/CD"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner:
        default: self-hosted
        description: ""
        options:
          - macos-latest
          - self-hosted
          - ubuntu-latest
        required: true
        type: choice

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  APP: skillpedia

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ${{ (inputs.runner == 'self-hosted' || inputs.runner == '') && fromJSON('["self-hosted", "skillpedia"]') || inputs.runner || fromJSON('["self-hosted", "skillpedia"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Build and deploy
        run: |
          npm install
          npm run build
          pm2 startOrRestart ecosystem.config.cjs
